project_name: v2tov3migrate

dist: .builds

before:
  hooks:
    - go mod tidy

builds:
  - id: build_noncgo
    main: ./
    binary: v2tov3migrate
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm

release:
  draft: true

archives:
  - id: archive_noncgo
    builds: [build_noncgo]
    format: zip
    files:
      - LICENSE.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
